name: Build DMJit for Linux

on:
  push:
    branches: ['main']
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  checkout-auxtools:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2
        with:
          repository: willox/auxtools
          path: auxtools-repo
      - name: Check directory
        run: ls -a
  build-dmjit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2
      - name: Build dmJIT
        run: docker build -f ./dockerbuild/ubuntu/dmjit/Dockerfile .