name: Build DMJit for Linux

on:
  push:
    branches: ['main']
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build-dmjit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout auxtools repository
        uses: actions/checkout@v2
        with:
          repository: ss220-space/auxtools
          ref: dm-jitaux
          path: auxtools-repo
      - name: Checkout current repository
        uses: actions/checkout@v2
        with:
          path: dmjit-repo
      - name: Check root
        run: pwd
      - name: Check directory
        run: ls -a
      - name: Build dmJIT
        run: docker build -f ./dmjit-repo/dockerbuild/ubuntu/dmjit/Dockerfile .