name: Build DMJit for Linux [Auto]

on:
  pull_request:
  
jobs:
  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          all_of: verified
          repo_token: ${{ secrets.GITHUB_TOKEN }}
  build-dmjit:
    uses: racer396/dmjit/.github/workflows/linux_build_dmjit.yaml@main
    with:
      byondVersion: '514'
      byondBuild: '1569'