name: Build DMJit for Linux [Auto]

on:
  push:
    branches: ['main']
  workflow_run:
    workflows: ["(Linux) Create and push Byond image"]
    types:
      - completed
  
jobs:
  build-dmjit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: ${{ GITHUB_REPOSITORY }}.github/workflows/linux_build_dmjit.yaml@main
        with:
          byondVersion: '514'
          byondBuild: '1583'