name: Build DMJit for Linux [Manual]

on:
  workflow_dispatch:
    inputs:
      byondVersion:
        description: 'Byond major version, like 514 in 514.1543 version'     
        required: true
        default: '514'
      byondBuild:
        description: 'Byond build version, like 1543 in 514.1543 version'     
        required: true
        default: '1583'
  
jobs:
  build-dmjit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
      - uses: ./.github/workflows/linux_build_dmjit.yaml
        with:
          byondVersion: ${{ github.event.inputs.byondVersion }}
          byondBuild: ${{ github.event.inputs.byondBuild }}