name: Build DMJit for Linux [Auto]

on:
  push:
    branches: ['main']
  workflow_run:
    workflows: ["(Linux) Create and push Byond image"]
    types:
      - completed
  
jobs:
  build-dmjit:
    uses: racer396/dmjit/.github/actions/dmjit-linux/build_dmjit.yaml@main
    with:
      byondVersion: '514'
      byondBuild: '1569'