name: Build DMJit for Linux

on:
  workflow_run:
    workflows: ["(Linux) Create and push Byond image"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      byondVersion:
        description: 'Byond major version, like 514 in 514.1543 version'     
        required: true
        default: '514'
      byondBuild:
        description: 'Byond build version, like 1543 in 514.1543 version'     
        required: true
        default: '1583'
  push:
    branches: ['main']
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build-dmjit:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/racer396/dmjit-llvm-rust-linux:main
      options: --user root
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout auxtools repository
        uses: actions/checkout@v3
        with:
          repository: ss220-space/auxtools
          ref: dm-jitaux
          path: auxtools
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          path: dmjit
      - name: Install zip
        run: apt-get install zip unzip
      - name: Download byond
        uses: suisei-cn/actions-download-file@v1
        id: downloadfile 
        with:
          url: "http://www.byond.com/download/build/${{ github.event.inputs.byondVersion }}/${{ github.event.inputs.byondVersion }}.${{ github.event.inputs.byondBuild }}_byond_linux.zip"
          target: ./
      - name: Create byond folder
        run: mkdir byond
      - name: Check root
        run: pwd
      - name: Check directory
        run: ls -a
      - name: Extract byond archive
        run: unzip ${{ github.event.inputs.byondVersion }}.${{ github.event.inputs.byondBuild }}_byond_linux.zip -d /byond
      - name: Make workdir dmjit
        run: cd dmjit
      - name: Set override
        run: rustup override set nightly-2021-11-05-i686-unknown-linux-gnu
        working-directory: ./dmjit
      - name: Run build
        run: cargo build
        working-directory: ./dmjit
      - name: Run tests
        run: cargo test
        working-directory: ./dmjit
        env:
          BYOND_PATH: /__w/dmjit/dmjit/byond