name: Build DMJit for Linux [Auto]

on:
  push:
    branches: ['main']
  workflow_run:
    workflows: ["(Linux) Create and push Byond image"]
    types:
      - completed
  
jobs:
  build-dmjit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
      - name: Check folder
        run: ls -a
      - uses: .github/workflows/linux_build_dmjit.yaml
        with:
          byondVersion: 514
          byondBuild: 1583