on:
  workflow_call:
    inputs:
      byondVersion:
        description: 'Byond major version, like 514 in 514.1543 version'
        required: true
        default: '514'
        type: string
      byondBuild:
        description: 'Byond build version, like 1543 in 514.1543 version'
        required: true
        default: '1569'
        type: string

jobs:
  build-dmjit:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/racer396/dmjit-llvm-rust-linux:main
      options: --user root
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout auxtools repository
        uses: actions/checkout@v3
        with:
          repository: ss220-space/auxtools
          ref: dm-jitaux
          path: auxtools
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          path: dmjit
      - name: Install zip
        run: apt-get install zip unzip
      - name: Download byond
        uses: suisei-cn/actions-download-file@v1
        id: downloadfile 
        with:
          url: "http://www.byond.com/download/build/${{ inputs.byondVersion }}/${{ inputs.byondVersion }}.${{ inputs.byondBuild }}_byond_linux.zip"
          target: ./
      - name: Create byond folder
        run: mkdir byond
      - name: Extract byond archive
        run: unzip ${{ inputs.byondVersion }}.${{ inputs.byondBuild }}_byond_linux.zip
      - name: Set override
        run: rustup override set nightly-2021-11-05-i686-unknown-linux-gnu
        working-directory: ./dmjit
      - name: Run build
        run: cargo build
        working-directory: ./dmjit
      - name: Generate test result and coverage report
        run: |
            cargo install cargo2junit grcov rust-covfix;
            cargo test -- -Z unstable-options --format json | cargo2junit > results.xml;
            zip -0 ccov.zip `find . \( -name "$PROJECT_NAME_UNDERSCORE*.gc*" \) -print`;
            grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" --ignore "tests/*" -o lcov.info;
            rust-covfix -o lcov_correct.info lcov.info;
        working-directory: ./dmjit
        env:
          BYOND_PATH: /__w/dmjit/dmjit/byond
          PROJECT_NAME_UNDERSCORE: dmjit_linux
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: -Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort
          RUSTDOCFLAGS: -Cpanic=abort
      - name: Upload test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          check_name: Test Results
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: ./dmjit/results.xml
      - name: Upload to CodeCov
        uses: codecov/codecov-action@v1
        with:
          # required for private repositories:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./dmjit/lcov.info
          fail_ci_if_error: true