name: Build DMJit for Linux [Manual]

on:
  workflow_dispatch:
    inputs:
      byondVersion:
        description: 'Byond major version, like 514 in 514.1543 version'     
        required: true
        default: '514'
      byondBuild:
        description: 'Byond build version, like 1543 in 514.1543 version'     
        required: true
        default: '1569'
  
jobs:
  build-dmjit:
    uses: racer396/dmjit/.github/actions/dmjit-linux/build_dmjit.yaml@main
    with:
      byondVersion: ${{ github.event.inputs.byondVersion }}
      byondBuild: ${{ github.event.inputs.byondBuild }}